import { Entity, PrimaryGeneratedColumn, Column, BeforeInsert, coreTypes } from '../shared/base.entity';

@Entity('type')
export default class TypeEntity {
  @PrimaryGeneratedColumn()
  uid: number;

  @Column({default: 'Create'})
  text: string;

  @BeforeInsert()
  isCoreType() {
    if (coreTypes.includes(this.text)) {
      this.isCore = true;
    }
  }
  /** If defined in https://www.w3.org/TR/activitystreams-vocabulary/#activity-types */
  @Column({default: false})
  isCore: boolean;

  /** Generated by ... Can be the URL of a Plugin */
  @Column({default: 'redaktor'})
  generator: string;
}
